/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.bu.dcharest;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * @author Don Charest
 */
public class NewAccount extends javax.swing.JFrame {

    /**
     * Creates new form NewAccount
     */
    public NewAccount() {
        initComponents();
    }

    DialogMessages dm = new DialogMessages();
    boolean isLoggedIn = false;
    boolean found;
    String username;
    String password;
    String data;
    String login;
    String user;
    String pass;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isLoggedIn() {
        return isLoggedIn;
    }

    public void setIsLoggedIn(boolean isLoggedIn) {
        this.isLoggedIn = isLoggedIn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        verPasswordTxt = new javax.swing.JPasswordField();
        openingBalTxt = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New User Account");

        jLabel1.setText("Enter Username: ");

        jLabel2.setText("Enter Password: ");

        jLabel3.setText("Verify Password:");

        jLabel4.setText("Openrning Balance:");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(openingBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(verPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(submitBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, submitBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(verPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(openingBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(submitBtn))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * Submit button on click will run tests on form data and if the there are
     * no issues, including: empty text fields, existing username, 
     * nonmatching passwords, or invalid number format, then two methods will 
     * be called: 
     * 1) createUserDataFile();
     * 2) createUserLogInFile();
     * finally, the form will be cleared and disposed.
     * @param evt 
     */
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        boolean caught = false;
        try {
            username = usernameTxt.getText();
            password = passwordTxt.getText();
            String verPass = verPasswordTxt.getText();
            // convert date object to string and reformat
            Date d = new java.util.Date();
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, YYYY");
            String date = sdf.format(d) + "\t";
            // convert balance to double, round to 2 plcs, and convert to string
            double openBalRaw = Double.parseDouble(openingBalTxt.getText());
            String rounded = String.format("%.2f", openBalRaw) + "\t";
            // create string of all user data, including preset file data -> to be saved to file
            data = "true\t" + date + "Opening Balance\t" + rounded + "other\t"
                    + "one time\t" + date + "1\t";
            // create string of user login detail (user & pass) -> to be saved to file
            login = username + "\t" + password + "\t";
            // check to see if user/pass fields have been completed
            if (!username.equals("") && !password.equals("") && !verPass.equals("")) {
                // check to see if username in use
                if (!readLoginFile()) {
                    if (password.trim().equals(verPass.trim())) {
                    } else {
                        // throw error message
                        dm.messagePasswordError();
                        caught = true;
                    }
                } else { // Username exists
                    JOptionPane.showMessageDialog(null, "Sorry Username: " + username + " is already taken",
                            "Status Message", JOptionPane.ERROR_MESSAGE);
                    caught = true;
                    clearLoginForm();
                }
            } else {
                // incomplete fields -> throw error message
                dm.messageFieldsIncomplete();
                caught = true;
            }
        } catch (HeadlessException e) {
            // throw error message
            dm.messageFieldsIncomplete();
            caught = true;
        } catch (NumberFormatException e) {
            // throw error message
            dm.messageNumberFormat();
            caught = true;
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!caught) {
            // everything is good -> create new user accct
            isLoggedIn = true;
            createUserDataFile();
            createUserLogInFile();
            dm.messageAccountCreated();
            clearLoginForm();
            dispose();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * Method to create a new user data file
     * Initial creation will include todays data and
     * an Opening Balance
     */
    private void createUserDataFile() {
        // file name will be "username_data_.txt"
        String filename = username + "_data.txt";
        String workingDirectory = System.getProperty("user.dir");
        // filepath will be the working directory of the project
        File file = new File(workingDirectory, filename);
        FileWriter fr = null;
        try {
            fr = new FileWriter(file);
            fr.write(data);
        } catch (IOException e) {
        } finally {
            //close resources
            try {
                fr.close();
            } catch (IOException e) {
            }
        }
    }

    /**
     * Method to clear new account form fields
     */
    private void clearLoginForm() {
        usernameTxt.setText("");
        passwordTxt.setText("");
        verPasswordTxt.setText("");
        openingBalTxt.setText("");
    }

    /**
     * Method to create and append data to user login file
     */
    private void createUserLogInFile() {
        String filename = "userLogInData.txt";
        String workingDirectory = System.getProperty("user.dir");
        FileWriter fr = null;
        File file = new File(workingDirectory, filename);
        try {
            fr = new FileWriter(file, true);
            fr.write(login);
        } catch (IOException e) {
        } finally {
            try {
                fr.close();
            } catch (IOException e) {
            }
        }
    }
    
    /**
     * Method to check if username already saved in file
     * @return true if name matched new user field text
     * @throws FileNotFoundException 
     */
    private boolean readLoginFile() throws FileNotFoundException {
        String filename = "userLogInData.txt";
        String workingDirectory = System.getProperty("user.dir");
        File file = new File(workingDirectory, filename);
        Scanner read = new Scanner(file);
        read.useDelimiter("\\n|\\t"); 
        while (read.hasNext()) {         
            user = read.next();
            // if user name exists -> return true
            if (username.trim().equals(user.trim())) {
                username = user.trim();
                found = true;// = true;
                return true;
            } 
        }
        return false;  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField openingBalTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JPasswordField verPasswordTxt;
    // End of variables declaration//GEN-END:variables
}
